# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

builds:
  - id: linux
    main: ./...
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
  - id: macOS
    main: ./...
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - arm64

archives:
  - formats: [binary]
    files: []
    name_template: >-
      {{ .Binary }}_{{ .Os }}_{{ .Arch }}

changelog:
  sort: asc

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
